name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
    test:
        name:  Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            julia_version: 
              - "1.9"
            os:
              - ubuntu-latest
              - macOS-latest
              - windows-latest
            arch:
              - x64
        
        steps:
            - uses: actions/checkout@v4

            - uses: julia-actions/setup-julia@latest
              with:
                version: ${{ matrix.julia_version }}
                arch: ${{ matrix.arch }}
            - uses: julia-actions/julia-buildpkg@latest
            - uses: julia-actions/julia-runtest@latest

    

                